### ISSUE TITLE
Spaces removed in latex string

### ISSUE THREAD

**Issue by viaudg** [stevengj/LaTeXStrings.jl#10]
On Ubuntu 14.04, Julia v0.4.6, latexstring("a b") will remove the space character and eventually produce the LaTeX string "ab" on a matplotlib figure, is that by design? I couldn't find a solution, neither "\ " or "\:" seemed to work, would you have an idea on how to fix this?

Many thanks,

**Comment by stevengj** [comment]
`latexstring("a b")` is equivalent to `LaTeXString("\$a b\$")` — as explained in the README, it automatically adds the enclosing `$...$`.   The space is not removed from the string, but LaTeX equation rendering ignores the space when it formats the equation.

If you want to force a space in a LaTeX equation, then use one of the [LaTeX spacing escapes](http://tex.stackexchange.com/questions/204178/how-to-obtain-even-space-between-variables-in-math-mode), like `L"a\,b"`.

If you want to force the string to be interpreted as text, not an equation, you can do `LaTeXString("a b")`.   But there is not much point in using `LaTeXString` at all if you just want text.

**Comment by viaudg** [comment]
Ok sorry I mistyped the second solution in my previous message, I indeed tried escaping in LaTeX equation with "\:" (or rather equivalently "\,"): that didn't work. But your message led me to try "\\:" and this worked.

**Comment by stevengj** [comment]
You need to escape the backslash if you use `latexstring`.  If you use `L"...."` you don't need the double backslash.

**Comment by viaudg** [comment]
Yes, that was my afterthought indeed. Thanks again and sorry for the inconvenience.
