### ISSUE TITLE
Latex not rendering with PyPlot v2.3.2, Julia v0.5.2, 

### ISSUE THREAD

**Issue by arturgower** [stevengj/LaTeXStrings.jl#14]
Hi there, great package. 

Any idea why this doesn't render properly:
```
  using LaTeXStrings
  using Plots
  pyplot()
  plot(0:1,0:1,annotations=(0.5,0.5, L"x_l"))
```
Though the underscore appears correctly, the font is not standard maths LaTeX. I have updated all packages.

Do you know is this a problem with PyPlot, Plots or your package?

Thanks,
Art

**Comment by stevengj** [comment]
It's definitely nothing to do with LaTeXStrings.

The following works fine for me in PyPlot:
```
using PyPlot
plot(0:1,0:1)
text(0.5,0.5,L"x_l")
```
If that fails for you, then it is a problem with your matplotlib installation.  If it succeeds for you (i.e. shows the subscript), then it is a problem with Plots.

**Comment by arturgower** [comment]
Good diagnosis. This test does not give any error, but also does not render LaTeX font. 
![figure_1](https://cloud.githubusercontent.com/assets/24454863/26548665/39595c80-446d-11e7-8c9d-84213f8cf974.png)

For some reason this test does work for `Plots` with the backend `pgfplots()` Any idea how I might fix this? I installed the latest version of matplotlib, PyPlot, LaTeXStrings and texlive. Here are some details:
```
julia> Pkg.installed("PyPlot")
v"2.3.2"
julia> Pkg.installed("LaTeXStrings")
v"0.2.1"
```

**Comment by stevengj** [comment]
I don't know what you mean by "does not render any LaTeX font".  It shows the 1 as a subscript, what more do you want?

Matplotlib does not actually use LaTeX itself as the rendering engine, it uses MathJAX with whatever fonts you have specified.

**Comment by stevengj** [comment]
Actually, you can configure Matplotlib to use LaTeX for text rendering if you want.  See: https://matplotlib.org/users/usetex.html

**Comment by stevengj** [comment]
You can also configure Matplotlib's mathtext to use LaTeX's computer-modern font: https://matplotlib.org/users/mathtext.html
