### ISSUE TITLE
changing the font size with {\small} and \begin{small} \end{small}

### ISSUE THREAD

**Issue by mantzaris** [stevengj/LaTeXStrings.jl#19]
Been having difficulty changing the font size of parts of the string and attempting to put it into the title of a plot with `using Plots` and either a pyplot or gr backend. The string is produced and do not know if the error is isolated in the figure plotting. A LaTeXString() or latexstring() or L""" """" produce the same error

julia> ll=LaTeXString("an equation;\$ 2+3 \\beta^3 }\$ \n \$\\begin{small} \\tau_4\\end{small}\$")
L"an equation;$ 2+3 \beta^3 }$ 
 $\begin{small} \tau_4\end{small}$"

julia> plot([1,2,3,4],[1,2,3,4],title=ll)
Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
ERROR: PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) <type 'exceptions.ValueError'>

**Comment by stevengj** [comment]
I assume you mean `ll=L"an equation;$ 2+3 \beta^3$ \n $\begin{small} \tau_4\end{small}$"`.  (If you pass a string directly to the `LaTeXString` constructor you need to escape the dollar signs etcetera.)

It looks like the error originates with Matplotlib.  The full error message for me starts with
```
PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, kw)) <type 'exceptions.ValueError'>
ValueError(u'\n\\begin{small} \\tau_4\\end{small}\n^\nUnknown symbol: \\begin (at char 0), (line:1, col:1)',)
```
Notice the `Unknown symbol: \begin` message: Matplotlib's LaTeX renderer only supports a subset of TeX syntax, and it appears that it does not support `\begin{small}`.

See also the Matplotlib manual (https://matplotlib.org/users/mathtext.html).  In particular, it is possible to switch Matplotlib to use `latex` itself to do the rendering: https://matplotlib.org/users/usetex.html#usetex-tutorial

**Comment by stevengj** [comment]
Closing since the problem here is not in LaTeXStrings
