### ISSUE TITLE
Escaping $ to interpolate variables in L"..."

### ISSUE THREAD

**Issue by jebej** [stevengj/LaTeXStrings.jl#27]
Would it make sense (or would it be even possible) to allow "escaping" `$`, either with a double `$$` or something else, to allow interpolation in `L"..."` strings? It would be convenient instead of having to fall back to using `latexstring` and needing to escape every `$` and `\`.

**Comment by stevengj** [comment]
I guess we could use `\$`

**Comment by BeastyBlacksmith** [comment]
Well, you can use `$` for interpolate and `\` for escaping and writing `\$` (in the final LaTeX string) would then be needed to be written as `\\\$` (like escaping in the shell).

**Comment by stillyslalom** [comment]
Another option would be extending `@sprintf` to allow its first argument to be a LaTeXString, with `%` as the interpolation/formatting character as usual. Compare:
```
latexstring("an equation: \$ $(round(c[1], digits=3)) + $(round(c[2], digits=3)) \\alpha^2 \$")
```
vs
```
@sprintf(L"an equation: $ %0.3f + %0.3f \alpha^2 $", c...)
```

**Comment by stillyslalom** [comment]
`@sprintf` needs a static format string (ref. https://github.com/JuliaLang/julia/issues/29278), so the above syntax wouldn't work. It works as expected with `Formatting.format`, though:
```
julia> s1 = L"an equation: $ {:.3f} + {:.3f} \alpha^2 $"
L"an equation: $ {:.3f} + {:.3f} \alpha^2 $"

julia> format(s1, 1, 2)
"an equation: \$ 1.000 + 2.000 \\alpha^2 \$"
```

**Comment by stevengj** [comment]
You can always just use an ordinary string and backslash-escape any backslashes and dollar signs…

**Comment by stillyslalom** [comment]
Of course, but I'd prefer to use LaTeXStrings, which are cleaner and more convenient than the backslash-escape alternative. This sort of behavior comes up all the time when creating plot labels/titles/annotations which include calculated coefficients.

**Comment by stevengj** [comment]
We could use `%$`, since that is a comment in LaTeX and is unlikely to appear in normal text, but it is a bit ugly.  Any other ideas?

**Comment by Moelf** [comment]
https://github.com/fonsp/Pluto.jl/issues/313

I hit the symptom of this in Pluto when trying to interpolate in `md"""`,

**Comment by stillyslalom** [comment]
@Moelf I think this is an issue on Markdown's end. You can work around your issue by directly accessing the string field:
```
julia> using Markdown, LaTeXStrings

julia> ls = L"y = mx + b";

julia> md"$(ls.s)"
"\$y = mx + b\$"
```

**Comment by Moelf** [comment]
@stillyslalom I don't know what customize the behavior when interpolated in string, but it is customizable (apart from what `print` gives you), then it should be customized in `LaTeXString` not in `Markdown` right?

**Comment by stillyslalom** [comment]
@Moelf To avoid the dependence of Markdown.jl (which is a stdlib package) upon LaTeXStrings.jl (which is not), it would need to be implemented here (or in a shim package), but that's entirely distinct from the issue at hand. It's probably best to open a new issue.

**Comment by Moelf** [comment]
I think I mis-read what this issue is about, oops, sry about the noise.
