### ISSUE TITLE
Package name LatexStrings

### ISSUE THREAD

**Issue by matthieugomez** [stevengj/LaTeXStrings.jl#29]
LatexStrings would be a better name for the package. I've just spent a few minutes trying to understand why the package won't download, because I mistyped the the exact casing.

**Comment by cscherrer** [comment]
IMO this is just something to get used to, because (weird as it is) it's the standard capitalization. You'll find it this way in many, many references:

https://www.latex-project.org/
https://en.wikipedia.org/wiki/LaTeX
https://www.overleaf.com/

**Comment by matthieugomez** [comment]
Yes that's fair.

**Comment by stevengj** [comment]
Tab completion also makes this easier
