### ISSUE TITLE
$$ appear when interpolating to axis label

### ISSUE THREAD

**Issue by leandromartinez98** [stevengj/LaTeXStrings.jl#30]
I am trying to use LaTeXStrings to add special characters to the label of a plot. The following results can be obtained:

`histogram!(xlabel=L"Test \alpha")`

Result: ![image](https://user-images.githubusercontent.com/31046348/64274988-f3ecea00-cf1a-11e9-8dd2-c2c7275a4ecd.png)

All text is interpreted as an equation, which is not satisfactory.

`histogram!(xlabel=L"\textrm{Test }\alpha")`

Result: ![image](https://user-images.githubusercontent.com/31046348/64275089-272f7900-cf1b-11e9-8f91-efe736503bfc.png)

Possibly the best alternative, but the fonts are different from the fonts of the rest of the plot.

`histogram!(xlabel="Test $(L"\alpha")")`

Result: 
![image](https://user-images.githubusercontent.com/31046348/64275213-7b3a5d80-cf1b-11e9-990f-4b21ef8ffacd.png)

This one looks very promising, because the special character (alpha) is rendered, and the fonts are not changed. However, the dollar signs appear. I could not get rid of them.

I am not sure if this an issue of the package or if there is a solution. I was able to find the following workaround:

```
string="$(L"Test \alpha")"
histogram!(xlabel=string[2:length(string)-1])
```
Result: 
![image](https://user-images.githubusercontent.com/31046348/64275835-e2a4dd00-cf1c-11e9-8d44-0d827d7b1e8f.png)

(unfortunately this option does not work to produce the Angstrom character (\AA))

Any thoughts? I could not find help anywhere else. I apologize already if this out of the scope of the issues.

**Comment by dav2017** [comment]
I have the same problem, but no solution.

**Comment by stevengj** [comment]
Same question was discussed on discourse: https://discourse.julialang.org/t/typing-special-characters-in-plot-legends-and-titles/24771/10?u=stevengj

The issue is that you are using the GR backend, which doesn't actually support LaTeX equations and hence it doesn't interpret the `$` that LaTeXStrings delimits equations with.
