### ISSUE TITLE
No project.toml

### ISSUE THREAD

**Issue by theogf** [stevengj/LaTeXStrings.jl#32]
The Compat.jl bounds clashes with other packages such as Turing like in https://github.com/JunoLab/LNR.jl/issues/4

**Comment by stevengj** [comment]
Closed by e9cba1c4dfecf2b032ae2c0d143d2fb0f8f5491f, I'll tag a new release soon.

**Comment by stevengj** [comment]
https://github.com/JuliaRegistries/General/pull/10181
