### ISSUE TITLE
error and warning on windows

### ISSUE THREAD

**Issue by AshtonSBradley** [stevengj/LaTeXStrings.jl#34]
On julia 1.3 and 1.4, and windows 10, using `LaTeXStrings` with the `gr` backend in `Plots`

`'latex' is not recognized as an internal or external command,
operable program or batch file.`

`latex: failed to create a dvi file`

This has appeared on a number of different systems. 

The first seems to be solved by `build LaTeXStrings`. 

The second seems to require `dvips` and it isn't clear to me how to install this on Windows. I assume it should get installed automatically as part of the build?

**Comment by stevengj** [comment]
It's an issue with the `gr` backend, not with LaTeXStrings, so you should report the problem there.
