### ISSUE TITLE
bug? Added an extra space

### ISSUE THREAD

**Issue by GitDeepSea** [stevengj/LaTeXStrings.jl#35]
hi,

`using Plots`
`using LaTeXStrings`
`p = plot(0:2,0:2, xlab = "xlabel: "*LaTeXString("\\gamma+\\alpha^2+1+\\alpha^2"), ylab = "ylabel: "*LaTeXString("1+\\alpha^2+1+\\alpha^2"))`

I get the figure
![QQ截图20200403185935](https://user-images.githubusercontent.com/34116981/78354057-ba2db000-75dd-11ea-9b8f-a4326124b425.png)

If try `p = plot(0:2,0:2,xlab = "xlabel: "*LaTeXString("1+\\alpha^2+1+\\alpha^2"))`, I get
![QQ截图20200403190853](https://user-images.githubusercontent.com/34116981/78354535-99b22580-75de-11ea-826d-e68e8f759fc9.png)

**Please keep attention on the xlabel and ylabel. It seems to exist an extra space in the label before first "+".**

Is it a bug?  Julia: Version 1.4.0 (2020-03-21); LaTeXStrings v1.1.0; Plots v0.29.4
Thank you!

**Comment by stevengj** [comment]
The LaTeX rendering is done by matplotlib (or technically by MathJax, I believe), not LaTeXStrings, so you should report complaints about their rendering there.

**Comment by stevengj** [comment]
Actually, what does the LaTeX rendering depends on your plotting backend, but in any case it is not the LaTeXStrings package.   Check your `Plots` backend and figure out the right place to file an issue.

**Comment by GitDeepSea** [comment]
Thank you. I am a new user of Julia. Now I understand that this issue is not caused by LaTeXStrings.
