### ISSUE TITLE
Support \displaystyle

### ISSUE THREAD

**Issue by mroavi** [stevengj/LaTeXStrings.jl#36]
I would like to display integrals and products in display mode since they look much better when the limits are included. I don't think that this feature is currently available. One way would be supporting the `\displaystyle` command (https://www.overleaf.com/learn/latex/display_style_in_math_mode). This is how the package `TikzPictures` does it.
```julia

tp = TikzPicture(L"""
\node[align=center, below, white] {
$ \displaystyle F(\omega) = \int_{-\infty}^{\infty} \! f(t)e^{-i \omega t} \, \mathrm{d}t $\\\\
$ F(\omega) = \displaystyle\int_{-\infty}^{\infty} \! f(t)\cos(\omega t) \mathrm{d}t - i \int_{-\infty}^{\infty} \! f(t)\sin(\omega t) \mathrm{d}t $\\\\
};
""", options="transform shape, scale=2.5", preamble="")
```
![image](https://user-images.githubusercontent.com/19517248/80849059-dbea7900-8c15-11ea-9d78-38b28923a8fb.png)

**Comment by stevengj** [comment]
LaTeXStrings does not do *any* formatting.  The *only* thing it does is allow you to easily construct strings containing LaTeX equations without have to do lots of escapes.

The formatting is the responsibility of whatever code you pass a LaTeXString to — e.g. if you pass it to matplotlib or display it in Jupyter it is rendered by MathJax.
