### ISSUE TITLE
Vector Hat Notation Appearing Off of a Letter

### ISSUE THREAD

**Issue by TheCedarPrince** [stevengj/LaTeXStrings.jl#38]
## Hello!

Hi @stevengj! Thanks for making such a wonderful tool and package. I ran into an issue, and tried to be as thorough as possible in reporting it. Let me know if you need any more info! Thanks!

## Problem

Ran into an issue today that does not appear to have been reported. I was working with Plots to label one of my plots as a unit vector (arrow over a character) and was using LaTeXStrings to do it. Up until now, I have had zero issues with the package. However, when I was trying to label my unit vector in the plot, here is what it appeared as:

![image](https://user-images.githubusercontent.com/29561456/86013507-383b0080-b9ed-11ea-8357-59547ef24d6c.png)

As you can see in the legend, the vectors `v` and `w`'s arrow hats are misaligned. Any thoughts as to why this is? 

## Code Used

Here is a segment of the code I used to generate this:

```julia
plot([0, v[1]],
     [0, v[2]],
     label = "v",
     arrow = :head,
     linewidth = 5);
plot!([0, w[1]],
     [0, w[2]],
     framestyle = :zerolines,
     title = "Visualizing Geometry of Vectors",
     label = "w",
     arrow = :head,
     linewidth = 5,
     legend = :best,
     xlim = (-8, 8),
     ylim = (-5, 5));
plot!([0, v⃗[1]],
     [0, v⃗[2]],
     label = L"$vec{v}$",
     arrow = :head,
     linewidth = 5);
plot!([0, w⃗[1]],
     [0, w⃗[2]],
     label = L"$vec{w}$",
     arrow = :head,
     linewidth = 5)
```

## Packages Info

```
  [7073ff75] IJulia v1.21.2
  [b964fa9f] LaTeXStrings v1.1.0
  [58dd65bb] Plotly v0.3.0
  [91a5bcdd] Plots v1.3.7
```

## System Information

```
          /:-------------:\          cedarprince@obsidian 
       :-------------------::        -------------------- 
     :-----------/shhOHbmp---:\      OS: Fedora x86_64 
   /-----------omMMMNNNMMD  ---:     Host: XPS 15 7590 
  :-----------sMMMMNMNMP.    ---:    Kernel: 5.6.13-100.fc30.x86_64 
 :-----------:MMMdP-------    ---\   Uptime: 20 hours, 37 mins 
,------------:MMMd--------    ---:   Shell: zsh 
:------------:MMMd-------    .---:   Resolution: 1920x1080, 1920x1080 
:----    oNMMMMMMMMMNho     .----:   DE: Plasma 
:--     .+shhhMMMmhhy++   .------/   WM Theme: Sweet-Dark-transparent 
:-    -------:MMMd--------------:    CPU: Intel i7-9750H (12) @ 4.500GHz 
:-   --------/MMMd-------------;     Memory: 6167MiB / 15639MiB 
:-    ------/hMMMy------------:
:-- :dMNdhhdNMMNo------------;
:---:sdNMMMMNds:------------:
:------:://:-------------::
:---------------------://
```

## Julia Information

```
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

**Comment by stevengj** [comment]
The LaTeXStrings package does not do any of the rendering; you should file an issue with your plotting backend.

**Comment by TheCedarPrince** [comment]
Thanks for the pointers @stevengj. Opened the issue there.
