### ISSUE TITLE
\textrm not working anymore in Julia 1.5

### ISSUE THREAD

**Issue by lmiq** [stevengj/LaTeXStrings.jl#39]
Example:
```
using Plots, LaTeXStrings
plot(title=L"Test \textrm{Test}")
```
On Julia 1.2:

![image](https://user-images.githubusercontent.com/31046348/90544079-ff9de480-e15c-11ea-9396-6ece3d4c6f6c.png)

On Julia 1.5:

![image](https://user-images.githubusercontent.com/31046348/90544474-8fdc2980-e15d-11ea-9506-b5cc3a893b75.png)

**Comment by stevengj** [comment]
LaTeX rendering is not done by LaTeXStrings, and is not done by Plots.  It is done by the Plots backend, so it depends on what backend you are using.  (e.g. PyPlot)?

**Comment by lmiq** [comment]
Using GR.
