### ISSUE TITLE
Rendering LaTeX strings

### ISSUE THREAD

**Issue by schneiderfelipe** [stevengj/LaTeXStrings.jl#43]
Hi @stevengj,

I'm looking for a way of rendering LaTeXStrings into images (to be used with, e.g., Images.jl or Luxor.jl). [Matplotlib](https://matplotlib.org/tutorials/text/usetex.html) seems to rely on dvipng and Ghostscript (and a LaTeX installation, of course 😄 ).

Can something like this be currently done with LaTeXStrings.jl? Thanks!

**Comment by stevengj** [comment]
LaTeXStrings itself doesn't do any rendering, and it isn't the right package for that.

Matplotlib does *not* use a LaTeX installation (by default) — see [this discussion on discourse](https://discourse.julialang.org/t/where-are-the-latex-equations-in-plots-coming-from/52148).

**Comment by stevengj** [comment]
(In particular, note that the GR package has a LaTeX math renderer.)

**Comment by schneiderfelipe** [comment]
> LaTeXStrings itself doesn't do any rendering, and it isn't the right package for that.
> 
> Matplotlib does _not_ use a LaTeX installation (by default) — see [this discussion on discourse](https://discourse.julialang.org/t/where-are-the-latex-equations-in-plots-coming-from/52148).

I misinterpreted Matplotlib's documentation. Thanks for sharing this link!

> (In particular, note from the discussion that the GR package has a LaTeX math renderer.)

That's interesting. I'll take a look at it.

**Comment by korsbo** [comment]
Latexify.jl also has some basic rendering of LaTeXStrings (`render(lsrt)`) - if that helps.

**Comment by schneiderfelipe** [comment]
> Latexify.jl also has some basic rendering of LaTeXStrings (`render(lsrt)`) - if that helps.

Awesome! This might solve my problem, thanks.
