### ISSUE TITLE
How to print a latexstring out

### ISSUE THREAD

**Issue by thudjx** [stevengj/LaTeXStrings.jl#52]
I am trying to print a latexstring using `LatexStrings` package:
`println(L"gap at \gamma is: %$(gap) eV")`
but get the following printed out:
`$gap at \gamma is: 0.08904209804025498 eV$`
which is not what I want. I know latexstring will work when plotting a figure using Plots . Why I cant print it in Latex style?

**Comment by stevengj** [comment]
LaTeXStrings does not do any LaTeX rendering; it just makes it easier to type the strings without escaping backslashes.  The LaTeX rendering is up to the display environment.

Moreover, `print` is for outputting text, and in general a LaTeX equation cannot be represented as plain text.   If you just want Greek letters, however, you can just type them directly in an ordinary string: `println("gap at γ is: %$(gap) eV")`
