### ISSUE TITLE
ArgumentError: regex matching is only available for the String type

### ISSUE THREAD

**Issue by mocalvao** [stevengj/LaTeXStrings.jl#55]
Hi all,

I used to use LaTeXStrings seamlessly, but I guess (not sure) the latest version v1.2.1 might have broken something. This simple MWE shouldt work, right?
```
using Plots
using LaTeXStrings
x = range(0, 10, length=100)
α = 1.0
plot(x, α*x, xaxis=L"x", yaxis=L"y", label=L"\alpha = %$α")
 ```
issuing the following error:

```
ArgumentError: regex matching is only available for the String type; use String(s) to convert

Stacktrace:
  [1] match(r::Regex, s::LaTeXString, i::Int64)
    @ Base ./regex.jl:317
  [2] match(r::Regex, s::LaTeXString)
    @ Base ./regex.jl:316
  [3] gr_inqtext(x::Int64, y::Int64, s::LaTeXString)
    @ Plots ~/.julia/packages/Plots/0FnGd/src/backends/gr.jl:231
...
```

Best

**Comment by stevengj** [comment]
It would certainly be possible to implement more `String` methods for the `LaTeXString` type…

**Comment by mocalvao** [comment]
It seems the issue is related to a GR problem:
[GR 0.62 and LaTeX](https://github.com/jheinen/GR.jl/issues/437)

**Comment by stevengj** [comment]
Regardless, I don't see why we can't support this.
