### ISSUE TITLE
Can I use a different font (like Palladio) in LaTeXStrings, and if so, how?

### ISSUE THREAD

**Issue by chrisoffner** [stevengj/LaTeXStrings.jl#58]
As my thesis uses the Palladio font, I'd like to have my Julia plots match it. Is there a way to use `LaTeXStrings` with a different font, and if so, how do I go about setting it?

**Comment by TS-CUBED** [comment]
This is similar to my question on MathTeXEngine:

https://github.com/Kolaru/MathTeXEngine.jl/issues/53 

so the answer seems to be: not at the moment

**Comment by TS-CUBED** [comment]
I'll need to check myself, but if using Matplotlib is an option, Matplotlib can be used in Julia, If used via pyCall, rather than through the Plots.jl package (or Makie, in my case), then all Matplotlib features should be available.

**Comment by stevengj** [comment]
This is a FAQ: https://github.com/stevengj/LaTeXStrings.jl/blob/master/README.md#faq-not-a-latex-renderer
