### ISSUE TITLE
Display equations are not centerred in Jupyter notebooks

### ISSUE THREAD

**Issue by newptcai** [stevengj/LaTeXStrings.jl#59]
If in a Jupyter/IJulia notebook, we write a code cell with the following lines
~~~L"""
$$
1 + 2 = 3
$$
"""
~~~
then the output is a math equation rendered by MathJax.
However, the equation is not centred in the output cell.

However, the following code
~~~
$$
1 + 2 = 3
$$
~~~
in a markdown cell results in an equation proper centred in the cell after it is rendered by Mathjax.

I am not sure if this a LaTeXStrings, IJulia or Jupyter problem though.

**Comment by stevengj** [comment]
This is a Jupyter issue.
