### ISSUE TITLE
Problem displaying a LaTeXString using a $ symbol inside

### ISSUE THREAD

**Issue by diegozea** [stevengj/LaTeXStrings.jl#60]
Hi! I have found this problem with Pluto & LaTeXStrings:

Example:

![image](https://user-images.githubusercontent.com/2822757/172022801-fc43ee3c-119e-41fa-a5ba-91566524d750.png)

Code:

```julia
### A Pluto.jl notebook ###
# v0.19.5

using Markdown
using InteractiveUtils

# ╔═╡ 0a05255c-e438-11ec-3566-77865b3fe6d8
using LaTeXStrings

# ╔═╡ 78067679-6a52-473f-bf96-657e0ca6d7f1
L"an equation: $1 + \alpha^2$"

# ╔═╡ 00000000-0000-0000-0000-000000000001
PLUTO_PROJECT_TOML_CONTENTS = """
[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"

[compat]
LaTeXStrings = "~1.3.0"
"""

# ╔═╡ 00000000-0000-0000-0000-000000000002
PLUTO_MANIFEST_TOML_CONTENTS = """
# This file is machine-generated - editing it directly is not advised

[[LaTeXStrings]]
git-tree-sha1 = "f2355693d6778a178ade15952b7ac47a4ff97996"
uuid = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
version = "1.3.0"
"""

# ╔═╡ Cell order:
# ╠═0a05255c-e438-11ec-3566-77865b3fe6d8
# ╠═78067679-6a52-473f-bf96-657e0ca6d7f1
# ╟─00000000-0000-0000-0000-000000000001
# ╟─00000000-0000-0000-0000-000000000002
```

**Comment by NNURLYGS** [comment]
I think it's probably the function _maybe_wrap_equation(s), because it's the one which warps the text with the latexstrnig formatting

**Comment by stevengj** [comment]
From the docs:
> Note that with latexstring(...) you do have to escape $ and \: for example, latexstring("an equation: \$1 + \\alpha^2\$").

**Comment by ederag** [comment]
```
latexstring("an equation: \$1 + \\alpha^2\$")
```
renders as
<img width="162" height="19" alt="Image" src="https://github.com/user-attachments/assets/ba1e21f7-a7b9-42ee-bc95-f2af184ddbcc" />,
just like the README and OP `L"an equation: $1 + \alpha^2$"`.

And I'd expect the `$` to be treated as the start of an equation (I think the OP did too).
Please reopen ?

**Comment by stevengj** [comment]
I think this is a bug with Pluto, where it expects text/latex to just be an equation, and not other text that contains an equation.  It works fine in Jupyter:

<img width="381" height="103" alt="Image" src="https://github.com/user-attachments/assets/a85f7a56-675a-4082-8089-8391a23ec8af" />

Remember, LaTeXStrings.jl doesn't do any formatting itself.  It is correctly creating the desired string here as far as I can tell:

<img width="559" height="86" alt="Image" src="https://github.com/user-attachments/assets/465d9de2-579a-4211-85af-3d7459186c42" />

It's just that Pluto is rendering it wrong.

**Comment by stevengj** [comment]
In particular, this seems to be https://github.com/JuliaPluto/Pluto.jl/issues/359

See also the discussion in https://github.com/JuliaStrings/LaTeXStrings.jl/issues/50
