### ISSUE TITLE
non-equations

### ISSUE THREAD

**Issue by shashi** [stevengj/LaTeXStrings.jl#8]
trying to use this in Escher and running into problems because of the surrounding `$`s. Some parsers don't like it:
```
Uncaught ParseError: KaTeX parse error: Unexpected character: '$' at position 0: ̲$a+b=c$
```
What's the best way to work around this? The dirty way is to remove the extra `$`s, the nice way I think maybe is to have both `LaTeXEquation` and `LaTeXString` types.

cc @alinchis

**Comment by stevengj** [comment]
Which parser accepts LaTeX equations but not dollar signs?

You could always strip off the `$` characters when you pass it to something else.

**Comment by shashi** [comment]
Yeah, I think that's what we'll do, thanks. Should it strip out `$`s at the end or all `$`s (not sure if there's any use for that in LaTeX equations)?

Looks like [KaTeX](https://khan.github.io/KaTeX/) only accepts equation inputs, so doesn't need `$`s.

**Comment by stevengj** [comment]
If it only accepts equation inputs, all of the strings should start and end with `$` and so you should just strip out the beginning and ending `$` (and throw an error if the beginning and ending characters are not `$`).    Potentially a LaTeX equation could contain a literal `\$`, so you wouldn't want to strip out `$` unconditionally.

**Comment by shashi** [comment]
Ok, thanks!

**Comment by stevengj** [comment]
Maybe it is useful to have an `equationstring(s::LaTeXString)` function in `LaTeXString` that does this?  A PR would be welcome.
